<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKhachSan_21_11" Class="tinhtienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QuanLyKhachSan_21_11;Integrated Security=True" SettingsObjectName="POS.Properties.Settings" SettingsPropertyName="QuanLyKhachSan_21_11ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.f_TongTienDichVu" Method="f_TongTienDichVu" IsComposable="true">
    <Parameter Name="MaKH" Parameter="maKH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.f_TongTienHoaDon" Method="f_TongTienHoaDon" IsComposable="true">
    <Parameter Name="MaKH" Parameter="maKH" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.f_TinhSoDem" Method="f_TinhSoDem" IsComposable="true">
    <Parameter Name="checkin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="checkout" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.f_CreateTableHoaDonChiTiet" Method="f_CreateTableHoaDonChiTiet" IsComposable="true">
    <Parameter Name="MaKH" Parameter="maKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenKH" Parameter="tenKH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SoPhong" Parameter="soPhong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SoDem" Parameter="soDem" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TenDV" Parameter="tenDV" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TienDV" Parameter="tienDV" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TienPhong" Parameter="tienPhong" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NgayDi" Parameter="ngayDi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CheckIn" Parameter="checkIn" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TongTien" Parameter="tongTien" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="f_CreateTableHoaDonChiTietResult">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TienDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TienPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CheckIn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>